packages:
  - packages/*

onlyBuiltDependencies:
  - electron
  - esbuild
  - keytar
  - node-pty

ignoredBuiltDependencies:
  - '@vscode/vsce-sign'

allowBuilds:
  '@vscode/vsce-sign': set this to true or false
  electron: set this to true or false
  esbuild: set this to true or false
  keytar: set this to true or false
  node-pty: set this to true or false
