export const IPC_CHANNELS = {
  SESSION_CREATE: 'session:create',
  SESSION_LIST: 'session:list',
  SESSION_SWITCH: 'session:switch',
  SESSION_DELETE: 'session:delete',
  QUERY_SEND: 'query:send',
  QUERY_ABORT: 'query:abort',
  QUERY_STREAM: 'query:stream',
  QUERY_TOOL_EVENT: 'query:tool-event',
  QUERY_COMPLETE: 'query:complete',
  QUERY_ERROR: 'query:error',
  QUERY_RETRYING: 'query:retrying',
  CONFIG_GET: 'config:get',
  CONFIG_SET: 'config:set',
  DIALOG_OPEN_FOLDER: 'dialog:open-folder',
  MCP_LIST_SERVERS: 'mcp:list-servers',
  MCP_RECONNECT: 'mcp:reconnect',
  MCP_TOGGLE: 'mcp:toggle',
  MCP_SAVE_CONFIG: 'mcp:save-config',
  SKILLS_LIST: 'skills:list',
  SESSION_SET_PERMISSION: 'session:set-permission-mode',
  SESSION_COMPACT: 'session:compact',
  SESSION_CLEAR: 'session:clear',
  SESSION_SET_THINKING: 'session:set-thinking',
  SESSION_SET_PLAN_MODE: 'session:set-plan-mode',
  SESSION_GET_PLAN_MODE: 'session:get-plan-mode',
  AGENT_PROGRESS: 'agent:progress',
  AGENT_TEXT: 'agent:text',
  AGENT_COMPLETE: 'agent:complete',
  AGENT_ABORT: 'agent:abort',
  FILE_GET_CHANGES: 'file:get-changes',
  FILE_GET_HISTORY: 'file:get-history',
  FILE_REWIND: 'file:rewind',
  FILE_REWIND_TURN: 'file:rewind-turn',
  FILE_ACCEPT: 'file:accept',
  FILE_ACCEPT_ALL: 'file:accept-all',
  PLAN_REVIEW: 'plan:review',
  PLAN_RESPOND: 'plan:respond',
  SESSION_GET_TASKS: 'session:get-tasks',
  SESSION_RENAME: 'session:rename',

  // Git
  GIT_BRANCH_LIST: 'git:branch-list',
  GIT_BRANCH_SWITCH: 'git:branch-switch',
  GIT_BRANCH_CREATE: 'git:branch-create',
  GIT_BRANCH_DELETE: 'git:branch-delete',
  GIT_STATUS: 'git:status',

  // App Launcher
  APPS_DETECT: 'apps:detect',
  APPS_OPEN: 'apps:open',

  // Terminal
  TERMINAL_CREATE: 'terminal:create',
  TERMINAL_WRITE: 'terminal:write',
  TERMINAL_RESIZE: 'terminal:resize',
  TERMINAL_DESTROY: 'terminal:destroy',
  TERMINAL_DATA: 'terminal:data',
  TERMINAL_EXIT: 'terminal:exit',

  // Model
  MODEL_TEST: 'model:test',
} as const
